In [1]:
import pandas as pd
import numpy as np

In [111]:
train_df = pd.read_csv('C:\\Users\\justin\\PycharmProjects\\Main_Test\Machine-Learning\\Housing Prices\\train.csv')
test_df = pd.read_csv('C:\\Users\\justin\\PycharmProjects\\Main_Test\\Machine-Learning\\Housing Prices\\test.csv')
print(train_df.head())

   Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg   
1   2          20       RL         80.0     9600   Pave   NaN      Reg   
2   3          60       RL         68.0    11250   Pave   NaN      IR1   
3   4          70       RL         60.0     9550   Pave   NaN      IR1   
4   5          60       RL         84.0    14260   Pave   NaN      IR1   

  LandContour Utilities    ...     PoolArea PoolQC Fence MiscFeature MiscVal  \
0         Lvl    AllPub    ...            0    NaN   NaN         NaN       0   
1         Lvl    AllPub    ...            0    NaN   NaN         NaN       0   
2         Lvl    AllPub    ...            0    NaN   NaN         NaN       0   
3         Lvl    AllPub    ...            0    NaN   NaN         NaN       0   
4         Lvl    AllPub    ...            0    NaN   NaN         NaN       0   

  MoSold YrSold  SaleType  SaleCondition  SalePrice  
0      2   2008     

In [112]:
train_df['Alley'].fillna(0, inplace=True)
train_df.Alley = train_df.Alley.astype('category')
train_df.Alley = train_df.Alley.cat.codes
test_df['Alley'].fillna(0, inplace=True)
test_df.Alley = test_df.Alley.astype('category')
test_df.Alley = test_df.Alley.cat.codes
print(train_df['Alley'].unique(), test_df['Alley'].unique())

[0 1 2] [0 2 1]


In [113]:
train_df.Street = train_df.Street.astype('category')
train_df.Street = train_df.Street.cat.codes
test_df.Street = test_df.Street.astype('category')
test_df.Street = test_df.Street.cat.codes
print(train_df.Street.unique(), test_df.Street.unique())

[1 0] [1 0]


In [114]:
train_df.LotShape = train_df.LotShape.astype('category')
train_df.LotShape = train_df.LotShape.cat.codes
test_df.LotShape = test_df.LotShape.astype('category')
test_df.LotShape = test_df.LotShape.cat.codes
print(train_df.LotShape.unique(), test_df.LotShape.unique())

[3 0 1 2] [3 0 1 2]


In [117]:
train_df.LandContour = train_df.LandContour.astype('category')
train_df.LandContour = train_df.LandContour.cat.codes
test_df.LandContour = test_df.LandContour.astype('category')
test_df.LandContour = test_df.LandContour.cat.codes
print(train_df.LandContour.unique(), test_df.LandContour.unique())

[3 0 2 1] [3 1 0 2]


In [119]:
train_df.Utilities = train_df.Utilities.astype('category')
train_df.Utilities = train_df.Utilities.cat.codes
test_df.Utilities = test_df.Utilities.astype('category')
test_df.Utilities = test_df.Utilities.cat.codes
print(train_df.Utilities.unique(), test_df.Utilities.unique())

[0 1] [1 0]


In [121]:
train_df.PoolQC = train_df.PoolQC.astype('category')
train_df.PoolQC = train_df.PoolQC.cat.codes
train_df['PoolQC'].fillna(0, inplace=True)
test_df.PoolQC = test_df.PoolQC.astype('category')
test_df.PoolQC = test_df.PoolQC.cat.codes
test_df['PoolQC'].fillna(0, inplace=True)
print(train_df.PoolQC.unique(), train_df.PoolQC.unique())

[0 1 2 3] [0 1 2 3]


In [122]:
train_df.MSZoning = train_df.MSZoning.astype('category')
train_df.MSZoning = train_df.MSZoning.cat.codes
test_df.MSZoning = test_df.MSZoning.astype('category')
test_df.MSZoning = test_df.MSZoning.cat.codes
print(train_df.MSZoning.unique(), train_df.MSZoning.unique())

[3 4 0 1 2] [3 4 0 1 2]


In [124]:
train_df.Fence = train_df.Fence.astype('category')
train_df.Fence = train_df.Fence.cat.codes
train_df['Fence'].fillna(0, inplace=True)
test_df.Fence = test_df.Fence.astype('category')
test_df.Fence = test_df.Fence.cat.codes
test_df['Fence'].fillna(0, inplace=True)
print(train_df.Fence.unique(), test_df.Fence.unique())

[0 3 2 1 4] [3 0 1 2 4]


In [125]:
train_df['MiscFeature'].fillna(0, inplace=True)
train_df.MiscFeature = train_df.MiscFeature.astype('category')
train_df.MiscFeature = train_df.MiscFeature.cat.codes
test_df['MiscFeature'].fillna(0, inplace=True)
test_df.MiscFeature = test_df.MiscFeature.astype('category')
test_df.MiscFeature = test_df.MiscFeature.cat.codes
print(train_df.MiscFeature.unique(), train_df.MiscFeature.unique())

[0 3 1 2 4] [0 3 1 2 4]


In [126]:
test_df.shape

(1459, 80)

In [127]:
varible_columns = ['Id', 'MSSubClass',  'MSZoning',  'LotArea',  'Street',  'Alley',  'LotShape',
                   'LandContour',  'Utilities', 'PoolArea', 'PoolQC', 'Fence', 'MiscFeature', 'YearBuilt', '1stFlrSF',
                   '2ndFlrSF', 'FullBath', 'BedroomAbvGr', 'TotRmsAbvGrd']

y = train_df.SalePrice
X = train_df[varible_columns]
print(X.head())

   Id  MSSubClass  MSZoning  LotArea  Street  Alley  LotShape  LandContour  \
0   1          60         3     8450       1      0         3            3   
1   2          20         3     9600       1      0         3            3   
2   3          60         3    11250       1      0         0            3   
3   4          70         3     9550       1      0         0            3   
4   5          60         3    14260       1      0         0            3   

   Utilities  PoolArea  PoolQC  Fence  MiscFeature  YearBuilt  1stFlrSF  \
0          0         0       0      0            0       2003       856   
1          0         0       0      0            0       1976      1262   
2          0         0       0      0            0       2001       920   
3          0         0       0      0            0       1915       961   
4          0         0       0      0            0       2000      1145   

   2ndFlrSF  FullBath  BedroomAbvGr  TotRmsAbvGrd  
0       854         2       

In [183]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.metrics import mean_absolute_error

train_X, val_X, train_y, val_y = train_test_split(X, y, random_state = 0)

In [129]:
print(test_df[varible_columns].head())
test_X[varible_columns].shape

     Id  MSSubClass  MSZoning  LotArea  Street  Alley  LotShape  LandContour  \
0  1461          20         2    11622       1      0         3            3   
1  1462          20         3    14267       1      0         0            3   
2  1463          60         3    13830       1      0         0            3   
3  1464          60         3     9978       1      0         0            3   
4  1465         120         3     5005       1      0         0            1   

   Utilities  PoolArea  PoolQC  Fence  MiscFeature  YearBuilt  1stFlrSF  \
0          1         0       0      3            0       1961       896   
1          1         0       0      0            1       1958      1329   
2          1         0       0      3            0       1997       928   
3          1         0       0      0            0       1998       926   
4          1         0       0      0            0       1992      1280   

   2ndFlrSF  FullBath  BedroomAbvGr  TotRmsAbvGrd  
0         0     

(1460, 19)

In [184]:
my_model = GradientBoostingRegressor(n_estimators=3000, learning_rate=0.05,
                                   max_depth=4, max_features='sqrt',
                                   min_samples_leaf=15, min_samples_split=10, 
                                   loss='huber', random_state =5)
my_model.fit(train_X, train_y)
test_X = test_df[varible_columns]
predicted_prices = my_model.predict(test_X)

In [176]:
def get_mae(max_leaf_nodes, predictors_train, predictors_val, targ_train, targ_val):
    model = RandomForestRegressor(max_leaf_nodes=max_leaf_nodes, random_state=0)
    model.fit(predictors_train, targ_train)
    preds_val = model.predict(predictors_val)
    mae = mean_absolute_error(targ_val, preds_val)
    return(mae)

In [180]:
for max_leaf_nodes in [50, 51, 52]:
    my_mae = get_mae(max_leaf_nodes, train_X, val_X, train_y, val_y)
    print("Max leaf nodes: %d  \t\t Mean Absolute Error:  %d" %(max_leaf_nodes, my_mae))

Max leaf nodes: 50  		 Mean Absolute Error:  24148
Max leaf nodes: 51  		 Mean Absolute Error:  24109
Max leaf nodes: 52  		 Mean Absolute Error:  24179


In [185]:
my_submission = pd.DataFrame({'Id': test_X.Id, 'SalePrice': predicted_prices})
my_submission.to_csv('submission.csv', index=False)